
version: '3'
services:
  lamp:
    image: tutum/lamp
    restart: always
    environment:
      MYSQL_PASS: mysql
    ports:
      - "3306:3306"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  neo4j:
    image: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
